### PR TITLE
add importprivkey and lasttx

### PR DESCRIPTION
**Pull request by justinvforvendetta**
we can have a function that will allow users to import a private key, and another function specifically for pulling up the transaction id that just took place upon withdraw success of user_session

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
something like this in the wallet:

if($_SESSION['user_session']!='')
		{
			try {
				$client = new Client($rpc_host, $rpc_port, $rpc_user, $rpc_pass);
				$result = $client->importPrivKey($_POST['privatekey'],$_SESSION['user_session']);
				 $_SESSION['successmsg']="Key imported successfully.";
			} catch (Exception $e) {
			// Do nothing
			 $_SESSION['msg']="Invalid private key.";
			}

**Comment by johnathanmartin** [comment]
Thanks for the suggestion, this is still on my todo list.

**Comment by justinvforvendetta** [comment]
cool. i was also thinking about adding webcam for importing privkey too, what do you think? i can add the import privkey input field to the wallet no problem, and maybe it would be nice to have a qrscan button next to it as well

**Comment by justinvforvendetta** [comment]
it might be useful to break this up into a few pieces come to think of it.

**Comment by justinvforvendetta** [comment]
i actually used this as the back end for $NLC when they hired me to do a web wallet, but i tore it apart quite a bit. split the code up into seperate files, new front end, email signup/email confirm for withdraw, php that logs users ip/port/host/browser on session, added importing privkeys, working on qr webcam scanner now. when i get a bit more done ill make some more pull requests here for features you can either merge or tear up a bit. i originally cloned it a very long time ago, and hadnt had a chance to really play with it until recently. it's really nice because it's so lite and very sturdy for an sql based wallet.

**Comment by johnathanmartin** [comment]
Closing poll request as the code pushed is not completed enough to provide any significant features. Feel free to open as an issue.

**Comment by bombeteste** [comment]
Hi, i'm trying to implement import/export privkey on the wallet. I checked this issue and i really want to know, if this work? In what part I implement this:

`if($_SESSION['user_session']!='')
{
try {
$client = new Client($rpc_host, $rpc_port, $rpc_user, $rpc_pass);
$result = $client->importPrivKey($_POST['privatekey'],$_SESSION['user_session']);
$_SESSION['successmsg']="Key imported successfully.";
} catch (Exception $e) {
// Do nothing
$_SESSION['msg']="Invalid private key.";
}
`

Any help would be appreciated. Thanks

**Comment by justinvforvendetta** [comment]
@brokercrypto this just makes it possible in the back end. you'd still need to add it to the UI.

**Comment by brokercrypto** [comment]
@justinvforvendetta  Thanks for replying. Is it possible for you to help me ? Where do i put the code above? wallet.php? 

How do i know that is working, because after i will implement to the UI.

**Comment by justinvforvendetta** [comment]
look at the commit above, not my paste in this thread

**Comment by brokercrypto** [comment]
@justinvforvendetta Sorry for taking your time. I saw your commit and i have done the same that you did. But i don't have sure if it's working.Big Thanks for your attention!!

**Pull request closed without merging**
